### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by paulywill** [paulywill/SeinfeldStratApp#1]
Which platform to build to maximize learning?

I think React, Vue, and Angular are very popular... and any one of those would be fun to learn.

What do you think @jefferson2z ?

**Comment by jefferson2z** [comment]
It seems Angular is used by more projects, but has some problems when changing versions, React has more learning resources and quite popular as well with no updating problems, and Vue is better for single page applications. Maybe React? Although I'm open to learn and use any of those.

**Comment by paulywill** [comment]
@jefferson2z React it is.
